### ISSUE TITLE
Error occurred while executing command

### ISSUE THREAD

**Issue by ziceptor** [Zerthick/Graveyards#1]
http://pastebin.com/2Qi9HByk

forge-1.10.2-12.18.1.2073-universal.jar
spongeforge-1.10.2-2073-5.0.0-BETA-1687.jar
Graveyards_v2.1.1.jar

**Comment by Zerthick** [comment]
I've having issues recreating this bug, what steps do you take to produce it? Was this the first time you had started up the plugin? Was this the first Graveyard you were trying to create? Or, were there several graveyards already in existence and this one just happened to null out?

**Comment by ziceptor** [comment]
I'm trying to create the first cemetery after installing the plugin.

**Comment by ziceptor** [comment]
Maybe this will help. The same error was from another plugin. Fixed.
http://pastebin.com/5XRHh12d
https://forums.spongepowered.org/t/tim-the-enchanter-api-4-0-0-and-5-0-0-snapshot/10662

**Comment by Zerthick** [comment]
Could you see if the bug is still there on the latest [release](https://github.com/Zerthick/Graveyards/releases/tag/v2.1.2)? Thanks!

**Comment by ziceptor** [comment]
Fixed. Thank you for your work!
