### ISSUE TITLE
The churchyard is not created

### ISSUE THREAD

**Issue by ziceptor** [Zerthick/Graveyards#2]
forge-1.11.2-13.20.0.2201-universal.jar
spongeforge-1.11.2-2201-6.0.0-BETA-2012.jar
Graveyards-v2.1.3.jar

1. /gy create name
2. A message appears stating that the churchyard was created.
3. Configuration files are not created:
- graveyardsData.config
- respawnData.config
4. Players do not respawn in the churchyard.

**Comment by ziceptor** [comment]
Any news?

**Comment by Zerthick** [comment]
Does the latest release still have the same issue?

**Comment by ziceptor** [comment]
Yes

**Comment by ziceptor** [comment]
Configs created after stopping the server. This is a potential problem of abnormal termination of the server.

**Comment by ziceptor** [comment]
After reboot worked. Immediately after creation does not work. I believe configs should be created after running /gy create name. And the churchyard should be carried out without restarting the server. If it is not possible to describe in the documentation creation process and explicitly specify the requirement to restart the server.

**Comment by Zerthick** [comment]
Yes if the server crashes then any graveyards created since the last time the server was restarted will be lost, this isn't really a bug, it's more of a design decision, many plugins choose to operate this way as it prevents unnecessary io operations while the server is running.

**Comment by ziceptor** [comment]
Note that graveyards did not work after creation. Earned only after reboot earned.

**Comment by Zerthick** [comment]
So you are saying that after executing `/graveyard create` and killing yourself, you did not spawn at a graveyard? This was before shutting down the server and generating the config?

**Comment by ziceptor** [comment]
Yes.

Sorry for my bad English. My native language is Russian.

It was like this:

1. The server is running.
2. Created a churchyard.
3. Kill a player. But was reborn in another place.. in the spawn. Expect to see him in the graveyard.
4. Check configs. They were not. Decided to restart the server.
5. During a stop of the server configs have been created.
6. The server is running.
7. Kill a player. Worked. The player is reborn in the graveyard.

Expected:

1. The server is running.
2. Created a graveyard.
7. Kill a player. Worked. The player is reborn in the graveyard.

That is, it took a restart of the server. Without it did not worked graveyards.

**Comment by Zerthick** [comment]
Haha, no worries I can understand you just fine. 😄 If it is indeed as you describe that is definitely a bug, I'll need to do some testing. One final question. When you executed `/graveyard create` did it show you a message that the graveyard had been successfully created?

**Comment by ziceptor** [comment]
Yes

**Comment by Zerthick** [comment]
I'm unable to replicate this behavior.

forge-1.11.2-13.20.0.2201-universal.jar
spongeforge-1.11.2-2201-6.0.0-BETA-2012.jar
Graveyards-v2.1.3.jar

Just because the config files are not created, the graveyards should still function as they are loaded into memory.  Do you have any other plugins/mods installed when you experience this bug?

**Comment by ziceptor** [comment]
API6-BetterBoom.jar
AutoBroadcasterSponge-0.2.1.jar
CommandBooks-v1.2.0.jar
CommandSigns-API-6.0.0-1.3.1.jar
CustomHeads-v1.0.3.jar
CustomPlayerCount.-.1.1.jar
EasyScoreboards.jar
EconomyLite-5.0.0-2.6.2.jar
FlexibleLogin.jar
foxcore-0.10.3-208-server.jar
foxguard-0.20.2-api5-347-server.jar
Graveyards-v2.1.3.jar
helpme-5.0.0-0.2.2.jar
holograms-v2.0.jar
HuskyCrates-0.1.0.jar
ipregister-0.0.3.jar
Launchpad-v1.0-FIXED.jar
MineskinSponge-v1.3.1.jar
MiscStuff-1.0-SNAPSHOT.jar
Nucleus-0.18.0-S5.1-1.10.2-plugin.jar
NucleusMixins-0.15.0-S5-mixinplugin.jar
PermissionsEx-Sponge.jar
PlayerShopsRPG-v1.0.1.jar
projectportals-5.1.0-0.13.6.jar
spongeforge-1.11.2-2201-6.0.0-BETA-2021.jar
Synonym-1.0.1.jar
TabCompleteMagic-2.0.0.jar
TitleMOTD.-.1.0.jar
treepers-5.1.3.jar
twentyticks.jar
walletdrop-5.1.0-0.2.1.jar
WinterWonderland-5.1.0-1.3.0.jar
worldedit-sponge-mc1.11-6.1.5-SNAPSHOT-dist.jar

I'll try to reproduce on the new server.

**Comment by ziceptor** [comment]
Yes, the problem is no more. Thank you for your patience!

**Comment by Zerthick** [comment]
No problem, glad it was fixed! 😄
