### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by TooVeryIcey** [Zerthick/Graveyards#3]
Hi,
I was wondering, is it possible for you to make an update where you need a permission to respawn at a certain graveyard, for example, on my server a player selects one of three classes, and I wanted it to be setup so that all players with the class of say...roman respawn at the roman graveyard no matter how far away they are...and if say a Saxon class dies, they respawn at the dragon graveyard...even if they die at the gate of a roman graveyard

**Comment by Zerthick** [comment]
Yes this is a feature I definitely intend to add at some point! Just have to find the time to sit down and write the code :smile:

**Comment by Zerthick** [comment]
Added in [v2.2.0](https://github.com/Zerthick/Graveyards/releases/tag/v2.2.0)! 😃
